### ISSUE TITLE
Little problem with Makefile

### ISSUE THREAD

**Issue by faxtarus** [ptitbigorneau/PB-ioq3-for-UrbanTerror-4.3#1]
Yop :)
When I launch ./Makefile, I have:

./Makefile: line 15: shell: command not found
/Makefile: line 17: syntax error near the unexpected symbol " $(COMPILE_PLATFORM),darwin ".
/Makefile: line 17: `ifeq ($(COMPILE_PLATFORM),darwin)'.

An idea?

Thx by advance.

**Comment by ptitbigorneau** [comment]
Ça se compile

Sous linux avec la commande « make »
Sous Windows en utilisant mingw et la comande « make »
[https://wiki.ioquake3.org/Building_ioquake3_on_Windows_-_mingw_and_msys](https://wiki.ioquake3.org/Building_ioquake3_on_Windows_-_mingw_and_msys)

**Comment by faxtarus** [comment]
J'ai bien modifié
ifndef COPYDIR
COPYDIR="/home/faxtarus/UTest"
endif
UTest est le répertoire où est installé le jeu.
make: ok
Création répertoire built dans PB-ioq3-for-UrbanTerror-4.3-master
J'ai loupé quelque chose?

**Comment by ptitbigorneau** [comment]
"COPYDIR"  n'a pas besoin d'être modifié. ça n'a pas l'air de changer le dossier ou est créé l'exécutable "Quake3-UrT-Ded.x86_64" 

il est créé dans le dossier "PB-ioq3-for-UrbanTerror-4.3-master/build/release-linux-x86_64/" ?

tu dois avoir ça a la fin de la compilation
```
LD build/release-linux-x86_64/Quake3-UrT-Ded.x86_64
make[2]: Leaving directory '/home/.../PB-ioq3-for-UrbanTerror-4.3-master'
make[1]: Leaving directory '/home/.../PB-ioq3-for-UrbanTerror-4.3-master'
```

**Comment by faxtarus** [comment]
Exact
Server UTest lancé avec Quake du built.
passw: xxx
Pas de bots.
Pub fonctionne

**Comment by ptitbigorneau** [comment]
Dans ton fichier "server.cfg":
```
set pb_mapslistbots "mapslistbots.txt"                       // Maps list with bots support
set pb_mapcyclebots "mapcyclebots.txt"                       // Name of mapcycle-file with bots
set pb_mapcycle "mapcycle.txt"                               // Name of your normal mapcycle-file
set pb_botsmapdefault "ut4_turnpike"                         // Map default with bots support
set pb_enablebots "on"                                       // Bots management on / off
set pb_autobots "on"                                         // on / off - automatically activates bots management when the server is empty 
set pb_botminplayers "4"                                     // minimum numbers of players (humans or bots) 

set bot_enable "1"
```

et les fichiers "mapslistbots.txt" et "mapcyclebots.txt" dans ton dossier ".q3a/q3ut4" 
[https://github.com/ptitbigorneau/PB-ioq3-for-UrbanTerror-4.3/tree/master/q3ut4](https://github.com/ptitbigorneau/PB-ioq3-for-UrbanTerror-4.3/tree/master/q3ut4)

**Comment by faxtarus** [comment]
Désolé, je viens de le faire et ça marche <3
Merci.
Il y a possibilité de renommer les bots?

**Comment by ptitbigorneau** [comment]
oui mais le plus simple c'est de passer par un fichier .pk3
genre -> [https://ptitbigorneau.fr/zzzzzzzzz_urtbots.pk3](https://ptitbigorneau.fr/zzzzzzzzz_urtbots.pk3)
tu le décompresses, tu as un fichier "bots.txt" dans le dossier "scripts" 
tu remplaces les noms dans "name" par ce que tu veux...  
tu refais un zip, que tu renommes ".pk3"
