### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by faxtarus** [ptitbigorneau/PB-ioq3-for-UrbanTerror-4.3#2]
Yop Ptitbig

1- Les bots ne sont pas pris en charge en FFA et GUNGAME.
2- Je voudrais supprimer des bots de la liste: Goose, Chicken, Rock entre autres.
3- Comment intégrer ton zzzz.pk3.
Une solution stp?
Fax

**Comment by ptitbigorneau** [comment]
- Pour les Bots en FFA et  en GuneGame, c'est de ma faute
avec cette modif ça devrait fonctionner -> [https://github.com/ptitbigorneau/PB-ioq3-for-UrbanTerror-4.3/commit/4c6a159e6bd3816f8b9939d882578f4cdc7d5ce5](url)

- Le fichier "zzzzzzzzz_urtbots.pk3" tu le mets avec tes maps dans le dossier "q3ut4/" ou ".q3a/q3ut4/"

"2- Je voudrais supprimer des bots de la liste: Goose, Chicken, Rock entre autres."
Je ne vois pas ce que tu veux faire ...

**Comment by faxtarus** [comment]
Merci pour la rectif :)
Sur mon Riyadh, je veux supprimer les bots avec G36 et PSG1 (chicken, scorpion...) et Goose est chiant.
J'ai sélectionné les Gears, mais je ne trouve pas ça suffisant: les bots se retrouvent sans arme principale.

**Comment by ptitbigorneau** [comment]
dans mon "pk3", il y a 15 bots configurés avec des LR, M4 et AK et 1 avec 1 G36.
au moins d'avoir plus de 16 bots, tu devrais avoir que des bots avec des LR, des M4 et des AK
pour le seul avec un G36, tu peux changer le "M" à la ligne "gear          fMAAXWR", dans le fichier bots.txt (dossier "scripts" dans le pk3) par "L" pour 1 LR ou "e" pour 1 M4 ou "a" pour 1 AK

**Comment by faxtarus** [comment]
Ok, le fichier "zzzzzzzzz_urtbots.pk3" est lu directement et remplace les bots du "zUrT43_020.pk3" ?
Je vais essayer de tester ça ce soir, je te dirai demain.
Merci beaucoup.

**Comment by ptitbigorneau** [comment]
oui normalement, je viens de tester avec 16 bots, j'avais que des LR, des M4 et des AK, juste 1 bot avec un G36

**Comment by faxtarus** [comment]
Les bots ne s'affichent pas en GG (j'en sais rien pour FFA, pas testé).
J'ai bien téléchargé ta dernière version d'il y a 2h pourtant.
Le Quake3-UrT-Ded.x86_64 généré fait la même taille que l'ancien.....

**Comment by ptitbigorneau** [comment]
verifie avec la commande /rcon bot_minplayers que tu n'as pas "0" et la meme chose pour pb_botminplayers.
chez moi ça fonctionne en FFA et en GunGame.

**Comment by faxtarus** [comment]
bot_minplayer is 0
pb_botminplayers is 6 default 0

**Comment by ptitbigorneau** [comment]
un petit /rcon bot_minplayers "6" devrait résoudre ton problème,
si il remet le bot_minplayers a 0, vérifie que tu as pb_enablebots sur "on"

**Comment by faxtarus** [comment]
/rcon bot_minplayers "6" ne change rien
pb_enablebots est bien sur "on"

**Comment by ptitbigorneau** [comment]
le nom de la map est dans le fichier "mapslistbots.txt" ?

**Comment by faxtarus** [comment]
Oui
Dés que je passe le server en tdm, ça fonctionne, je le repasse en GG: pas de bots.

**Comment by ptitbigorneau** [comment]
je viens de corriger, le problème de comptage des joueurs en FFA, en GunGame
c'est peut être ça ton problème.

**Comment by faxtarus** [comment]
Ok c'est bon.
Merci beaucoup pour tout ce que tu fais encore pour nous.
Sincèrement.
Fax :)
